CREATE TABLE IF NOT EXISTS `wechat`.`img_group` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `group_name` VARCHAR(45) NULL DEFAULT '未分组',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 15
DEFAULT CHARACTER SET = utf8
COMMENT = '图片的分组'

CREATE TABLE IF NOT EXISTS `wechat`.`material` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `img_name` VARCHAR(100) NULL DEFAULT NULL,
  `img_url` VARCHAR(300) NOT NULL,
  `group_id` INT(11) NULL DEFAULT '1',
  `material_id` VARCHAR(100) NULL DEFAULT NULL,
  `local_name` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 27
DEFAULT CHARACTER SET = utf8